

ParseConfig = {
    "action_parser":"!!",
    "value_parser":"**",
    "time_parser":"@@",
    "end_parser":"##"
}


MENU_BTN = {
    "LogType":{
        "label":"登記/補登",
        "text":"Menu!!LogType",
        "data":"A&登記/補登"
    },
    "Log":{
        "label":"登記",
        "text":"Menu!!Log",
        "data":"A&登記"
    },
    "LogHistory":{
        "label":"補登",
        "text":"Menu!!LogHistory",
        "data":"A&補登"
    },
    "QueryType":{
        "label":"查詢",
        "text":"Menu!!QueryType",
        "data":"A&查詢"
    },
    "Settings":{
        "label":"設定",
        "text":"Menu!!Settings",
        "data":"A&設定"
    },
    "Suggestions":{
        "label":"建議",
        "text":"Menu!!Suggestions",
        "data":"A&建議"
    },
    "ReminderType":{
        "label":"提醒設定",
        "text":"Menu!!ReminderType",
        "data":"A&提醒設定"
    },
    "BabyCustoms":{
        "label":"寶寶設定",
        "text":"Menu!!BabyCustoms",
        "data":"A&寶寶設定"
    },
    "LogHistoryOther":{
        "label":"體重/體溫/身高/頭圍",
        "text":"Menu!!LogHistoryOther",
        "data":"A&體重/體溫/身高/頭圍"
    },
    "LogOther":{
        "label":"體重/體溫/身高/頭圍",
        "text":"Menu!!LogOther",
        "data":"A&體重/體溫/身高/頭圍"
    },
    "QueryTypeAll":{
        "label":"詳細記錄",
        "text":"Menu!!QueryTypeAll",
        "data":"A&詳細記錄"
    },
    "QueryTypeSum":{
        "label":"統計紀錄",
        "text":"Menu!!QueryTypeSum",
        "data":"A&統計紀錄"
    }
}

LOG_BTN = {
    "Feed":{
        "label":"餵奶",
        "text":"Log!!Feed**",
        "data":"A&餵奶"
    },
    "Daiper1":{
        "label":"小便",
        "text":"Log!!Daiper**1",
        "data":"A&小便"
    },
    "Daiper2":{
        "label":"大便",
        "text":"Log!!Daiper**2",
        "data":"A&大便"
    },
    "Weight":{
        "label":"體重",
        "text":"Log!!Weight**",
        "data":"A&體重"
    },
    "Height":{
        "label":"身高",
        "text":"Log!!Height**",
        "data":"A&身高"
    },
    "Temperature":{
        "label":"體溫",
        "text":"Log!!Temperature**",
        "data":"A&體溫"
    },
    "HeadLength":{
        "label":"頭圍",
        "text":"Log!!HeadLength**",
        "data":"A&頭圍"
    }
}


LOGHISTORY_BTN = {
    "Feed":{
        "label":"餵奶",
        "text":"LogHistory!!Feed**",
        "data":"A&餵奶"
    },
    "Daiper1":{
        "label":"小便",
        "text":"LogHistory!!Daiper**1",
        "data":"A&小便"
    },
    "Daiper2":{
        "label":"大便",
        "text":"LogHistory!!Daiper**2",
        "data":"A&大便"
    },
    "Weight":{
        "label":"體重",
        "text":"LogHistory!!Weight**",
        "data":"A&體重"
    },
    "Height":{
        "label":"身高",
        "text":"LogHistory!!Height**",
        "data":"A&身高"
    },
    "Temperature":{
        "label":"體溫",
        "text":"LogHistory!!Temperature**",
        "data":"A&體溫"
    },
    "HeadLength":{
        "label":"頭圍",
        "text":"LogHistory!!HeadLength**",
        "data":"A&頭圍"
    }
}

QUERY_ALL_BTN = {
    "Feed&Daiper":{
        "label":"進食與尿布",
        "text":"QueryAll!!Feed&Daiper**",
        "data":"A&進食與尿布"
    },
    "Weight&Temperature":{
        "label":"體重與體溫",
        "text":"QueryAll!!Weight&Temperature**",
        "data":"A&體重與體溫"
    },
    "Height&HeadLength":{
        "label":"身高與頭圍",
        "text":"QueryAll!!Height&HeadLength**",
        "data":"A&身高與頭圍"
    },

}

QUERY_SUM_BTN = {
    "Feed&Daiper":{
        "label":"進食與尿布",
        "text":"QuerySum!!Feed&Daiper**",
        "data":"A&進食與尿布"
    }
}

PERIOD_BTN = {
    "1":{
        "label":"今日",
        "text":"1",
        "data":"A&今日"
    },
    "7":{
        "label":"一週",
        "text":"7",
        "data":"A&一週"
    },
    "30":{
        "label":"一個月",
        "text":"30",
        "data":"A&一個月"
    },
    "90":{
        "label":"三個月",
        "text":"90",
        "data":"A&三個月"
    }
}

SUGGESTIONS_BTN = {
    "NextFeed":{
        "label":"下次進食時間",
        "text":"Suggestions!!NextFeed",
        "data":"A&下次進食時間"
    },
    "FeedVolume":{
        "label":"建議奶量",
        "text":"Suggestions!!FeedVolume",
        "data":"A&建議奶量"
    },
    "SleepingTime":{
        "label":"建議睡眠時數",
        "text":"Suggestions!!SleepingTime",
        "data":"A&建議睡眠時數"
    },
}

BABYCUSTOM_BTN = {
    "Birthday":{
        "label":"生日",
        "text":"BabyCustoms!!Birthday**",
        "data":"A&生日"
    },
    "Gender":{
        "label":"性別",
        "text":"BabyCustoms!!Gender**",
        "data":"A&性別"
    },
    "FeedInterval":{
        "label":"餵奶間隔時間",
        "text":"BabyCustoms!!FeedInterval**",
        "data":"A&餵奶間隔時間"
    },
    "FeedFrequency":{
        "label":"每日餵奶次數",
        "text":"BabyCustoms!!FeedFrequency**",
        "data":"A&每日餵奶次數"
    },
}

REMINDER_BTN = {
    "Feed":{
        "label":"設定提醒餵奶",
        "text":"Reminder!!Feed**",
        "data":"A&設定提醒餵奶"
    },
    "Daiper":{
        "label":"設定提醒換尿布",
        "text":"Reminder!!Daiper**",
        "data":"A&設定提醒換尿布"
    },
    "CancelFeed":{
        "label":"取消提醒餵奶",
        "text":"Reminder!!Feed**-1",
        "data":"A&取消提醒餵奶"
    },
    "CancelDaiper":{
        "label":"取消提醒換尿布",
        "text":"Reminder!!Daiper**-1",
        "data":"A&取消提醒換尿布"
    },
}