name: Docker Image CI

on:
  push:
    tags:
      - '[0-9].[0-9]'
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU ${{github.ref_name}}
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: rejectsgallery/baby_tracker:${{github.ref_name}}
